# Generated by Django 3.0.8 on 2021-02-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
                ('int_grp', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
